[project]
name = 'Biometric-Security-Insurance-Platform'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.biometric-accuracy-oracle]
path = 'contracts/biometric-accuracy-oracle.clar'
clarity_version = 3
epoch = '3.2'

[contracts.privacy-compliance-validator]
path = 'contracts/privacy-compliance-validator.clar'
clarity_version = 3
epoch = 'latest'

[contracts.security-breach-detector]
path = 'contracts/security-breach-detector.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
